### ISSUE TITLE
link expired for Synthetic data Generation

### ISSUE THREAD

**Issue by rabbit200** [WPZgithub/ESPRA#1]
the link you provide for generating synthetic data: http://www.yurulin.com/download/code/facetnet.html has expired, do you know a new one, or can you upload its source code?

**Comment by WPZgithub** [comment]
> the link you provide for generating synthetic data: http://www.yurulin.com/download/code/facetnet.html has expired, do you know a new one, or can you upload its source code?

@rabbit200 Hi! Please check the 'gen_syn.m' code file.

**Comment by rabbit200** [comment]
> > the link you provide for generating synthetic data: http://www.yurulin.com/download/code/facetnet.html has expired, do you know a new one, or can you upload its source code?
> 
> @rabbit200 Hi! Please check the 'gen_syn.m' code file.

Hi! Thank you for your reply, but your code https://github.com/WPZgithub/ESPRA/blob/master/gen_syn2.m can only generate dynamic networks with fixed number of communities. Can you upload the original source code of facetnet? Or do you know a new link?

**Comment by WPZgithub** [comment]
Hi, @rabbit200! You are right. My code 'gen_syn2.m' can only generate networks with fixed number of communities. My code was modified from [Facetnet](http://www.yurulin.com/download/code/facetnet.html), which also did not provide synthentic dynamic networks with changing number of communities. Since this is an earlier project, we did not generate more realistic dynamic networks. However, I think you can check other packages, such as (https://cdlib.readthedocs.io/en/latest/reference/cd_algorithms/temporal_clustering.html) and (https://tnetwork.readthedocs.io/en/latest/reference/generation.html).

**Comment by rabbit200** [comment]
> Hi, @rabbit200! You are right. My code 'gen_syn2.m' can only generate networks with fixed number of communities. My code was modified from [Facetnet](http://www.yurulin.com/download/code/facetnet.html), which also did not provide synthentic dynamic networks with changing number of communities. Since this is an earlier project, we did not generate more realistic dynamic networks. However, I think you can check other packages, such as (https://cdlib.readthedocs.io/en/latest/reference/cd_algorithms/temporal_clustering.html) and (https://tnetwork.readthedocs.io/en/latest/reference/generation.html).

"Guys like you never go out of style", thank you, sincerely!
